### ISSUE TITLE
Launch Toolbar breaks on certain launches

### ISSUE THREAD

**Issue by cirept** [cirept/salesforceToolbar#10]
The launch toolbar doesn't work on this launch

https://cdk.my.salesforce.com/a1E0b000003JfgY

Pull Request
#11

**Comment by cirept** [comment]
It looks like the owner of the launch is causing issues with the toolbar.  The code can't find what it needs to in order to create the "email" and "chat" tool

**Comment by chongjunkim** [comment]
Created a Pull request with the quick fix. (not sure if you can link the pull request here)
